# Generated by Django 2.0.7 on 2018-07-31 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2048)),
                ('attendees', models.ManyToManyField(to='rsvp_bot.Attendee')),
            ],
        ),
        migrations.CreateModel(
            name='EventBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=256)),
                ('expiration', models.IntegerField()),
                ('events', models.ManyToManyField(to='rsvp_bot.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('discord_id', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='users',
            field=models.ManyToManyField(to='rsvp_bot.User'),
        ),
        migrations.AddField(
            model_name='eventboard',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp_bot.Server'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp_bot.User'),
        ),
    ]
